// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      this.gameover = __bind(this.gameover, this);
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      this.set('playerScore', 0);
      this.set('dealerScore', 0);
      return this.setListeners();
    };

    App.prototype.gameover = function(playerVictory) {
      var deck;
      if (playerVictory === null) {
        alert('tie');
      } else if (playerVictory === true) {
        this.set('playerScore', this.get('playerScore') + 1);
        alert('player wins!');
      } else {
        this.set('dealerScore', this.get('dealerScore') + 1);
        alert('player loses!');
      }
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      return this.setListeners();
    };

    App.prototype.setListeners = function() {
      this.get('playerHand').on('stand', (function(_this) {
        return function() {
          var dealer, playerHand;
          playerHand = _this.get('playerHand');
          dealer = _this.get('dealerHand');
          return dealer.play(playerHand.scores()[0]);
        };
      })(this));
      this.get('playerHand').on('bust', (function(_this) {
        return function() {
          return _this.gameover(false);
        };
      })(this));
      this.get('dealerHand').on('bust', (function(_this) {
        return function() {
          return _this.gameover(true);
        };
      })(this));
      this.get('dealerHand').on('win', (function(_this) {
        return function() {
          return _this.gameover(true);
        };
      })(this));
      this.get('dealerHand').on('loss', (function(_this) {
        return function() {
          return _this.gameover(false);
        };
      })(this));
      return this.get('dealerHand').on('tie', (function(_this) {
        return function() {
          return _this.gameover(null);
        };
      })(this));
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
